pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
  - name: Automatic merge on dependabot PR after success CI
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - '#commits-behind=0' # Only merge up to date pull requests
      - check-success=actions.ci (build windows-latest)
      - check-success=actions.ci (build ubuntu-latest)
      - check-success=actions.ci (build macos-latest)
      - check-success=build (windows-latest)
      - check-success=build (ubuntu-latest)
      - check-success=build (macos-13)
      - check-success=build (macos-14)
    actions:
      merge:
  - name: Thank contributor
    conditions:
      - merged
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
