pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
  - name: Automatic merge on dependabot PR after success CI
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build (windows-latest)
      - check-success=build (ubuntu-latest)
      - check-success=build (macos-latest)
    actions:
      merge:
        method: rebase
        strict: smart
  - name: Thank contributor
    conditions:
      - merged
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
