pull_request_rules:
  - name: Automatic merge on dependabot success PR
    conditions:
      - author=dependabot
      - check-success=CI / build (windows-latest) (pull_request)
      - check-success=CI / build (ubuntu-latest) (pull_request)
      - check-success=CI / build (macos-latest) (pull_request)
    actions:
      merge:
        method: rebase
        strict: smart
  - name: Thank contributor
    conditions:
      - merged
    actions:
      comment:
        message: "Thank you @{{author}} for your contribution!"
