name: GitTools
description: Build tasks for easy semantic versioning for projects using Git and release management.
author: GitTools
branding:
  color: gray-dark
  icon: git-pull-request
runs:
  using: node12
  main: dist/github/setup/index.js
