name: 'Publish Azure Extension'
description: 'Publish Azure Extension to Marketplace'
inputs:
  mode:
    description: 'Release mode'
    required: true
  major:
    description: 'Major version'
    required: true
  minor:
    description: 'Minor version'
    required: true
  patch:
    description: 'Patch version'
    required: true
  token:
    description: 'Token for Azure DevOps'
    required: true

outputs:
  vsix:
    description: 'Path to the generated VSIX file'
    value: ${{ steps.publish-azure.outputs.vsix }}

runs:
  using: 'composite'
  steps:
    -   name: Publish Azure extension
        id: publish-azure
        shell: pwsh
        run: |
          . .\utilities.ps1 # Import the functions

          publish-vsix  -mode ${{ inputs.mode }} -token ${{ inputs.token }} -major ${{ inputs.major }} -minor ${{ inputs.minor }} -patch ${{ inputs.patch }}
