name: gitversion-execute
description: GitHub Action for Easy Semantic Versioning with GitVersion. Execute GitVersion to obtain version information
author: GitTools
branding:
  color: gray-dark
  icon: git-pull-request
runs:
  using: node20
  main: main.mjs
inputs:
  targetPath:
    description: Optionally supply the path to the working directory
    required: false
    default: ''
  disableCache:
    description: Whether to disable GitVersion cache
    required: false
    default: 'false'
  disableNormalization:
    description: Whether to disable GitVersion normalization
    required: false
    default: 'false'
  disableShallowCloneCheck:
    description: Whether to disable the check for shallow clone
    required: false
    default: 'false'
  configFilePath:
    description: Optional path to config file (defaults to GitVersion.yml)
    required: false
  overrideConfig:
    description: |
        Optional override for the configuration file. This should be newline-separated key-value pairs, e.g.:
        update-build-number=false
        next-version=1.0.0
    required: false
    default: ''
  updateAssemblyInfo:
    description: Whether to update versions in the AssemblyInfo files
    required: false
    default: 'false'
  updateAssemblyInfoFilename:
    description: Update versions in specified file
    required: false
    default: ''
  updateProjectFiles:
    description: Whether to update versions in the project files
    required: false
    default: 'false'
outputs:
  major: # id of output
    description: 'The Major value'
  minor:
    description: 'The Minor value'
  patch:
    description: 'The Patch value'
  preReleaseTag:
    description: 'The PreReleaseTag value'
  preReleaseTagWithDash:
    description: 'The PreReleaseTagWithDash value'
  preReleaseLabel:
    description: 'The PreReleaseLabel value'
  preReleaseNumber:
    description: 'The PreReleaseNumber value'
  weightedPreReleaseNumber:
    description: 'The WeightedPreReleaseNumber value'
  buildMetaData:
    description: 'The BuildMetaData value'
  fullBuildMetaData:
    description: 'The FullBuildMetaData value'
  majorMinorPatch:
    description: 'The MajorMinorPatch value'
  semVer:
    description: 'The SemVer value'
  assemblySemVer:
    description: 'The AssemblySemVer value'
  assemblySemFileVer:
    description: 'The AssemblySemFileVer value'
  fullSemVer:
    description: 'The FullSemVer value'
  informationalVersion:
    description: 'The InformationalVersion value'
  branchName:
    description: 'The BranchName value'
  escapedBranchName:
    description: 'The EscapedBranchName value'
  sha:
    description: 'The Sha value'
  shortSha:
    description: 'The ShortSha value'
  versionSourceSha:
    description: 'The VersionSourceSha value'
  commitsSinceVersionSource:
    description: 'The CommitsSinceVersionSource value'
  uncommittedChanges:
    description: 'The UncommittedChanges value'
  commitDate:
    description: 'The CommitDate value'
