name: gitreleasemanager-addasset
description: GitHub Action for creating and exporting releases for software applications hosted on GitHub. Adds assets to a release
author: GitTools
branding:
  color: gray-dark
  icon: git-pull-request
runs:
  using: node20
  main: main.mjs
inputs:
  repository:
    description: The name of the repository in the format owner/repo
    required: true
    default: ''
  token:
    description: The access token to access GitHub with
    required: true
    default: ''
  milestone:
    description: The milestone to use
    required: true
    default: ''
  assets:
    description: Path(s) to the file(s) to include in the release
    required: true
    default: ''
  targetDirectory:
    description: The directory on which GitReleaseManager should be executed. Defaults to current directory
    required: false
    default: ''
  logFilePath:
    description: Path to where log file should be created. Defaults to logging to console.
    required: false
    default: ''
