name: gitreleasemanager-setup
description: GitHub Action for creating and exporting releases for software applications hosted on GitHub. Installs the specific version of GitReleaseManager.Tool
author: GitTools
branding:
  color: gray-dark
  icon: git-pull-request
runs:
  using: node20
  main: main.js
inputs:
  versionSpec:
    description: Required version in the form of 0.17.x or exact version like 0.17.0
    required: true
    default: ''
  includePrerelease:
    description: Include pre-release versions when matching a version
    required: false
    default: 'false'
  ignoreFailedSources:
    description: Treat package source failures as warnings.
    required: false
    default: 'false'
  preferLatestVersion:
    description: Prefer to download the latest version matching the versionSpec, even if there is a local cached version.
    required: false
    default: 'false'
