name: gitversion-command
description: GitHub Action for Easy Semantic Versioning with GitVersion. Run GitVersion with arguments.
author: GitTools
branding:
  color: gray-dark
  icon: git-pull-request
runs:
  using: node20
  main: main.mjs
inputs:
  targetPath:
    description: Optionally supply the path to the working directory
    required: false
    default: ''
  disableShallowCloneCheck:
    description: Whether to disable the check for shallow clone
    required: false
    default: 'false'
  arguments:
    description: Arguments to send to GitVersion
    required: true
    default: ''
