name: example-7
on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  GitVersion_v6_same_job:
    name: GitVersion v6 (same job)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.3
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.3

      - run: |
          echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
        name: Display GitVersion variables (without prefix)

      - run: |
          echo "FullSemVer (env.GitVersion_FullSemVer) : ${{ env.GitVersion_FullSemVer }}"
        name: Display GitVersion variables (with prefix)

      - run: |
          echo "FullSemVer (steps.version_step.outputs.fullSemVer)            : ${{ steps.version_step.outputs.fullSemVer }}"
        name: Display GitVersion outputs (step output without prefix)

      - run: |
          echo "FullSemVer (steps.version_step.outputs.GitVersion_FullSemVer) : ${{ steps.version_step.outputs.GitVersion_FullSemVer }}"
        name: Display GitVersion outputs (step output with prefix)

      - run: |
          echo "FullSemVer (env.myvar_fullSemVer)            : ${{ env.myvar_fullSemVer }}"
        name: Display mapped local env (outputs without prefix)
        env:
          myvar_fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}

      - run: |
          echo "FullSemVer (env.myvar_GitVersion_FullSemVer) : ${{ env.myvar_GitVersion_FullSemVer }}"
        name: Display mapped local env (outputs with prefix)
        env:
          myvar_GitVersion_FullSemVer: ${{ steps.version_step.outputs.GitVersion_FullSemVer }}

      - run: |
          echo "FullSemVer (env.myvar_fullSemVer)            : $env:myvar_fullSemVer"
        name: Display mapped local env (pwsh - outputs without prefix)
        shell: pwsh
        env:
          myvar_fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}

      - run: |
          echo "FullSemVer (env.myvar_GitVersion_FullSemVer) : $env:myvar_GitVersion_FullSemVer"
        name: Display mapped local env (pwsh - outputs with prefix)
        shell: pwsh
        env:
          myvar_GitVersion_FullSemVer: ${{ steps.version_step.outputs.GitVersion_FullSemVer }}

      - run: |
          echo "FullSemVer (myvar_fullSemVer)            : $myvar_fullSemVer"
        name: Display mapped local env (bash - outputs without prefix)
        shell: bash
        env:
          myvar_fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}

      - run: |
          echo "FullSemVer (myvar_GitVersion_FullSemVer) : $myvar_GitVersion_FullSemVer"
        name: Display mapped local env (bash - outputs with prefix)
        shell: bash
        env:
          myvar_GitVersion_FullSemVer: ${{ steps.version_step.outputs.GitVersion_FullSemVer }}
