name: Update GitVersion version

permissions:
  contents: read

on:
  repository_dispatch:
    types: [ gitversion-release-published ]

defaults:
  run:
    shell: pwsh

jobs:
  update-gitversion-version:
    if: ${{ github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: gittools/cicd/checkout@v1
        with:
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          fetch-depth: 1

      - run: |
          . ./utilities.ps1 # Import the functions

          $version = "${{ github.event.client_payload.newTag }}"

          $oldTag = extract-version
          $newTag = ($version -split '\.')[0,1] -join '.' | % { "$_.x" }

          echo "Updating GitVersion version to $newTag"
          echo "Old version: $oldTag"
          echo "New version: $newTag"

          dir -r .\docs\**\*.md   | % { update-files $_ -OldVersion $oldTag -NewVersion $newTag }
          dir -r .github\**\*.yml | % { update-files $_ -OldVersion $oldTag -NewVersion $newTag }
          dir -r .azure\**\*.yml  | % { update-files $_ -OldVersion $oldTag -NewVersion $newTag }

        name: Update GitVersion version

      - uses: gittools/cicd/git-commit-push@v1
        with:
          message: "update GitVersion version to ${{ github.event.client_payload.newTag }}"
        name: Commit and push updated GitVersion version
