name: output-example-1

permissions:
  contents: read

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  GitVersion_v6_same_job:
    name: GitVersion v6 (same job)
    runs-on: ubuntu-24.04
    steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@bc6623af8fc07d5a8903052dd46da33403eec8e8 # v4.5.0
        with:
          versionSpec: '6.7.x'

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@bc6623af8fc07d5a8903052dd46da33403eec8e8 # v4.5.0

      - run: |
          echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
        name: Display GitVersion variables (without prefix)

      - run: |
          echo "FullSemVer (env.GitVersion_FullSemVer) : ${{ env.GitVersion_FullSemVer }}"
        name: Display GitVersion variables (with prefix)

      - run: |
          echo "FullSemVer (steps.version_step.outputs.fullSemVer)            : ${{ steps.version_step.outputs.fullSemVer }}"
        name: Display GitVersion outputs (step output without prefix)

      - run: |
          echo "FullSemVer (steps.version_step.outputs.GitVersion_FullSemVer) : ${{ steps.version_step.outputs.GitVersion_FullSemVer }}"
        name: Display GitVersion outputs (step output with prefix)

      - run: |
          echo "FullSemVer (env.myvar_fullSemVer)            : ${{ env.myvar_fullSemVer }}"
        name: Display mapped local env (outputs without prefix)
        env:
          myvar_fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}

      - run: |
          echo "FullSemVer (env.myvar_GitVersion_FullSemVer) : ${{ env.myvar_GitVersion_FullSemVer }}"
        name: Display mapped local env (outputs with prefix)
        env:
          myvar_GitVersion_FullSemVer: ${{ steps.version_step.outputs.GitVersion_FullSemVer }}

      - run: |
          echo "FullSemVer (env.myvar_fullSemVer)            : $env:myvar_fullSemVer"
        name: Display mapped local env (pwsh - outputs without prefix)
        shell: pwsh
        env:
          myvar_fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}

      - run: |
          echo "FullSemVer (env.myvar_GitVersion_FullSemVer) : $env:myvar_GitVersion_FullSemVer"
        name: Display mapped local env (pwsh - outputs with prefix)
        shell: pwsh
        env:
          myvar_GitVersion_FullSemVer: ${{ steps.version_step.outputs.GitVersion_FullSemVer }}

      - run: |
          echo "FullSemVer (myvar_fullSemVer)            : $myvar_fullSemVer"
        name: Display mapped local env (bash - outputs without prefix)
        shell: bash
        env:
          myvar_fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}

      - run: |
          echo "FullSemVer (myvar_GitVersion_FullSemVer) : $myvar_GitVersion_FullSemVer"
        name: Display mapped local env (bash - outputs with prefix)
        shell: bash
        env:
          myvar_GitVersion_FullSemVer: ${{ steps.version_step.outputs.GitVersion_FullSemVer }}
